### ISSUE TITLE
Reconnection impossible after bluetooth bug...

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#36] opened 2018-03-05 11:41 UTC
Hi

As I expressed in the comments of issue #31, I have the following bug : 

When bluetooth connection crashes, the antenna trie by itself to reconnect after a few seconds. Sometime the reconnection is successfull, sometine not. In this second case, the antenna stops flashing. I call startBluetoothPairingIfPossible, but nothing happens, and I have to switch it off and switch on to get a new connection

Below the debug information : I stay blocked at the last line "receiveGotennaState: 93" even if I send startBluetoothPairingIfPossible

03-05 12:26:53.937 29608-29608/fr.myapp D/ViewRootImpl@4fa170b[ParametresActivity]: ViewPostImeInputStage processPointer 0
03-05 12:26:54.008 29608-29608/fr.myapp D/ViewRootImpl@4fa170b[ParametresActivity]: ViewPostImeInputStage processPointer 1
03-05 12:26:54.009 29608-29608/fr.myapp D/GOTENNA: CHANGE ANTENNA
03-05 12:26:54.010 29608-29608/fr.myapp I/GTEventNotifier: CLEARED GOTENNA ADDRESS
03-05 12:26:54.010 29608-29608/fr.myapp D/GOTENNA_CONNECT: startBluetoothPairingIfPossible
03-05 12:26:54.014 29608-29608/fr.myapp I/GTEventNotifier: INITIATING SCAN FOR GOTENNA: ANY
03-05 12:26:54.015 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.016 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.017 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.020 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.020 29608-29608/fr.myapp D/BluetoothLeScanner: Stop Scan
03-05 12:26:54.021 2992-3526/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler: fr.myapp, msg: MESSAGE_STOP_SCAN
03-05 12:26:54.026 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.028 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.028 29608-29608/fr.myapp D/BluetoothLeScanner: Start Scan
03-05 12:26:54.029 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.030 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.031 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.032 29608-29608/fr.myapp D/BluetoothAdapter: STATE_ON
03-05 12:26:54.137 29608-29620/fr.myapp D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=7 mClientIf=0
03-05 12:26:54.148 2992-3526/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler: fr.myapp, msg: MESSAGE_START_SCAN
03-05 12:26:54.185 29608-29608/fr.myapp D/GOTENNA_CONNECT: CONNECTION STATE UPDATED
03-05 12:26:54.185 29608-29608/fr.myapp D/GOTENNA: SCANNING
03-05 12:26:54.186 29608-29608/fr.myapp D/receiveGotennaState: 93

I already reported this issue in #31 but I didn't have the debug information. This is a real blocking ppoint because my customer that uses gotenna put it in a bag or a pocket. He has to open the bag, remove is gloves, restart the antenna, and put again the gloves. This is not ergonomic and not user friendly...

I also would like to have some feedback about issue #31 : when will it be solved ???  I'm still waiting for a date, can you give us more information?

**Comment by rahulsubu** [comment] 2018-03-05 22:07
Issue #31 will be resolved in the next release of the App/FW.
Targeting End of April/Early May.

**Comment by ZeDvD** [comment] 2018-04-22 18:49
Can you give us the date of the next release that will solve this issue ? We are now end of April, do you have more information ?

**Comment by tcolligan-ap** [comment] 2018-04-23 15:46
@ZeDvD The issue should be resolved in the next release of the Mesh App/FW. Targeting mid to late June.

**Comment by benhirashima** [comment] 2018-05-31 04:13
This bug is really killing the user experience in GliderLink. My users use the app for hours on end, and they have to power cycle the goTenna several times an hour to work around this issue. Please get it fixed as soon as possible!

**Comment by ZeDvD** [comment] 2018-06-09 21:36
Hi, can you give us a delivery date for this bug fix ?

**Comment by dsuresh-ap** [comment] 2018-12-12 23:46
Pro SDK for Android has been released. iOS is still in beta and will follow shortly. Please create a new issue if the problem is not fixed.

**Closed by dsuresh-ap** 2018-12-12 23:46 UTC
Labels: bug
